version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: InterfazChatBot
    ports:
      - '5002:5002'
    volumes:
      - .:/app
      - /app/node_modules
    
networks:
  default:
    name: microsvcs
    external: true
